// OiL! CONTENT — GENERATED by scripts/build_oil_content.py from the
// design toolkit (oil_home_game/data.py). Do not hand-edit; rerun the script.
// STATUS: all gameplay numbers are CONCEPT. The 14 OPEN_RULES are the
// designer's to close — this build never silently fills them (House Rule 5).
const OIL = {
 "GAME": {
  "title": "OiL! THE HOME GAME",
  "subtitle": "The Combustible Anders Engine Spiral",
  "publisher": "Anders & Partners",
  "publisher_slogan": "Double-Check Your Career",
  "designer": "Joseph Coleman, Anders & Partners LLC",
  "player_term": "Speculators",
  "players_min": 4,
  "players_max": 6,
  "age_min": 14,
  "dice_core": 3,
  "dice_expansion": 4,
  "dice_model": "A:three-body-emergent-price",
  "dice_names_core": [
   "Supply",
   "Weather",
   "World"
  ],
  "dice_name_expansion": "Green Anders",
  "decks": [
   "DEEDS",
   "FREEDOM-MARKET",
   "COMPETITION"
  ],
  "layers": [
   "LOGISTICS",
   "CRISIS",
   "MYTH"
  ]
 },
 "FACTIONS": [
  {
   "code": "HARTSTARR",
   "brand": "Hartstarr / Big Hartmart",
   "region": "USA — South / heartland",
   "observed": "gold star roundel; 'BIG HARTMART'; 'FUEL UP. GO FAR.'; Texas highway, Waco signage; mega travel-center",
   "design_read": "American heartland / Texas big-box fuel-and-snacks (Buc-ee's x Texaco register)",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "STOCK",
   "brand": "Stock Oil",
   "region": "USA — Northeast / Wall Street",
   "observed": "flaming-torch roundel; Manhattan skyline; classic forecourt",
   "design_read": "American Wall Street legacy supermajor (Standard Oil / Exxon register); finance capital",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "MC",
   "brand": "Milecastle",
   "region": "UK / Europe",
   "observed": "'MC' roundel + tricolor swoosh; White Cliffs of Dover; 'FUEL | COFFEE | ESSENTIALS'",
   "design_read": "British motorway-forecourt major (BP / Shell register)",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "BRIGHT",
   "brand": "Bright (合)",
   "region": "China",
   "observed": "'BRIGHT 合' roundel; Shanghai skyline; Chinese road/service-area signage; dense neon",
   "design_read": "Chinese national champion (Sinopec / PetroChina register)",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "MINA",
   "brand": "Mina Gaz (МИНА ГАЗ)",
   "region": "Post-Soviet — Russian state sphere",
   "observed": "'МИНА ГАЗ' Cyrillic; steppe; Soviet bus-stop mosaic; Lada",
   "design_read": "Post-Soviet state gas (Gazprom register). Note: 'мина' = landmine/mine in Russian — built-in double meaning",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "NIK",
   "brand": "Nikoyl (НИКОЙЛ)",
   "region": "Post-Soviet — private/oligarch sphere",
   "observed": "'НИКОЙЛ' Cyrillic; grey overcast; decayed roadside station",
   "design_read": "Post-Soviet oligarch oil (Lukoil register); grim/depleted aesthetic",
   "edition": "CORE",
   "mechanical_role": null
  },
  {
   "code": "PETRO_SUR",
   "brand": "Petro Sur",
   "region": "South America — Venezuela",
   "observed": "red 'P' monogram (flame/derrick) + 'PETRO SUR' wordmark; forecourt sign 'Energía para Venezuela'; Caracas tower-block murals ('CARACAS ES ENERGÍA', 'ENERGÍA SOBERANÍA FUTURO', 'DEL SUR NACE NUESTRA FUERZA'); octane board in bolívars; red + white + gold (FACTION REFS/PETRO SUR)",
   "design_read": "Latin-American state petro-nationalist (PDVSA / Petrobras register); resource-sovereignty propaganda aesthetic",
   "edition": "EXPANSION",
   "mechanical_role": null
  },
  {
   "code": "HADDAD",
   "brand": "Haddad Energy",
   "region": "Middle East — Gulf",
   "observed": "gold vertical emblem (stacked derricks / 'H') on black; 'HADDAD ENERGY'; Khamis Haddad, Founder & Chairman (Gulf executive, white thobe); Dubai skyline, refineries, superyacht; gold-on-black luxury. Taglines: 'We don't move markets. We steady them.' / 'We shape the flow.' / 'Private Capital. Public Trust. Shared Future.' (FACTION REFS/HADDAD)",
   "design_read": "Gulf sovereign-wealth supermajor (Aramco / ADNOC / sovereign-fund register); stability-as-power, luxury institutional",
   "edition": "EXPANSION",
   "mechanical_role": null
  }
 ],
 "CARDS": [
  {
   "name": "If I Say I'm An Oil Man",
   "deck": "DEEDS",
   "type": "Legendary Asset",
   "effects": [
    "claim contested territory",
    "force payment from competitors",
    "raise global tension"
   ],
   "theme": "authority through ownership",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Texas Tea",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "increased barrel production",
    "temporary extraction bonus",
    "environmental pressure increase"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Ocean of Oil",
   "deck": "DEEDS",
   "type": "Asset / Mythic Event",
   "effects": [
    "massive resource gain",
    "regional control bonus",
    "collapse pressure increase"
   ],
   "theme": "",
   "tags": [
    "MYTH",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "...And It's All Mine",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "claim complete region",
    "monopoly bonus",
    "increased hostility"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Get Yer Own",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "deny access to infrastructure",
    "block shared usage"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Juice Tanker",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "mobile storage",
    "additional inventory capacity",
    "spill risk if destroyed"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": true,
   "status": "CONCEPT"
  },
  {
   "name": "For The Love Of The Craft",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "gain bonus from refining",
    "ignore one penalty from production"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "All Yours",
   "deck": "DEEDS",
   "type": "Asset",
   "effects": [
    "transfer liability",
    "pass crisis effect to another player"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Strait Flush",
   "deck": "FREEDOM-MARKET",
   "type": "Market Event",
   "effects": [
    "close Hormuz / Panama / Suez",
    "block transit"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "one of the strongest names in the set",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Split Tea",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "break trade agreements",
    "divide shipping routes"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Ocean of Serenity",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "lower tensions",
    "pause escalation",
    "temporary calm"
   ],
   "theme": "",
   "tags": [
    "MYTH"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "It's Just A Little Chop",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "minor disruption",
    "hidden escalation"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Ocean of Time",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "delay projects",
    "freeze movement",
    "extend countdowns"
   ],
   "theme": "",
   "tags": [
    "MYTH",
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "I've Travelled Across For You",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "ignore route restrictions",
    "long-distance delivery bonus"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Cash Wave",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "everyone gains money",
    "inflation pressure rises"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Rogue Wave",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "destroy cargo",
    "damage fleets",
    "wipe inventory"
   ],
   "theme": "",
   "tags": [
    "CRISIS",
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Doldrums",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "no movement next round",
    "tankers stall"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Chiiiiiiiina",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "supply flood",
    "lower prices",
    "hurt high-price strategies"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Cymbals and Gongs",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "market spectacle",
    "narrative distraction",
    "price manipulation"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Up And Fill",
   "deck": "FREEDOM-MARKET",
   "type": "",
   "effects": [
    "immediate delivery bonus",
    "rapid extraction"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Force Majeure",
   "deck": "COMPETITION",
   "type": "Global Event",
   "effects": [
    "cancel ongoing effects",
    "trigger random disruption",
    "reset conditions"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "potential benchmark card",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Leviathan Knows",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "reveal hands",
    "inspect assets",
    "force card play"
   ],
   "theme": "surveillance",
   "tags": [
    "MYTH"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Hobbesian",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "no cooperation",
    "no trades",
    "hostile territory state"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Locke'd In",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "protect ownership",
    "prevent seizure",
    "freeze claims"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Ocean of Monsters",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "random chaos",
    "unknown threat",
    "escalation table"
   ],
   "theme": "",
   "tags": [
    "MYTH",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Ocean of Fire",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "regional war",
    "infrastructure loss",
    "price surge"
   ],
   "theme": "",
   "tags": [
    "MYTH",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Stop Laughing!",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "cancel success",
    "force reroll",
    "interrupt action"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Catastrophe",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "major disaster",
    "multi-region impact"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "No Words.",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "no table negotiation",
    "no diplomacy phase"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Smoke Stack",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "increased production",
    "increased environmental pressure"
   ],
   "theme": "",
   "tags": [
    "CRISIS",
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Stringent",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "new regulations",
    "reduced production",
    "increased costs"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Measured Austerity",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "controlled reduction",
    "lower demand",
    "lower revenue"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Boots On The Ground",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "secure territory",
    "raise hostility"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS",
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Dog-Wagged",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "small action causes large effect",
    "reverse expected outcome"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Tugger, No!",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "cancel movement",
    "disable transport"
   ],
   "theme": "",
   "tags": [
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Drones R Us",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "disable asset",
    "remote strike",
    "escalation risk"
   ],
   "theme": "",
   "tags": [
    "CRISIS",
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "The Titan Shifts",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "move megastructure",
    "reshape strategic map"
   ],
   "theme": "",
   "tags": [
    "MYTH",
    "LOGISTICS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Oligarcheology",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "remove influence",
    "seize resources",
    "political disruption"
   ],
   "theme": "\"A man falls. The system remains.\"",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Quiet Over Peace",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "lower visible conflict",
    "increase hidden collapse pressure"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Gulf-Faw",
   "deck": "COMPETITION",
   "type": "",
   "effects": [
    "regional conflict",
    "global price increase"
   ],
   "theme": "",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  },
  {
   "name": "Negotiating With A Worthy Adversary",
   "deck": "COMPETITION",
   "type": "Global Event",
   "effects": [
    "narrative distraction / media spectacle",
    "manipulate price in the player's favor",
    "nothing structural changes — no real negotiation",
    "self-dealing on camera (legitimacy cost)"
   ],
   "theme": "the American President negotiates with the only adversary he respects — himself, on a 40-inch screen; the cameras roll while the world depletes",
   "tags": [
    "CRISIS"
   ],
   "design_notes": "Designer-authored 2026-06-13. Satirical recurring-figure card (the American President watching himself on TV). COMPETITION spectacle register (cf. Cymbals and Gongs / Dog-Wagged).",
   "shared_with_ersn": false,
   "status": "CONCEPT"
  }
 ],
 "EDD": {
  "name": "E.D.D. PROTOCOL",
  "subtitle": "Eat / Divide / Destroy",
  "status": "CONCEPT",
  "trigger_conditions": [
   "oil price exceeds critical threshold",
   "global instability condition met"
  ],
  "resolution_roll": {
   "EAT": [
    "absorb competitor asset",
    "acquire territory",
    "seize infrastructure"
   ],
   "DIVIDE": [
    "split region",
    "force treaty",
    "break alliance",
    "fragment ownership"
   ],
   "DESTROY": [
    "remove asset",
    "disable route",
    "eliminate infrastructure"
   ]
  },
  "design_goal": "late-game predatory capitalism mechanic; potential centerpiece system",
  "critical_price_threshold": null,
  "instability_condition_value": null,
  "roll_table": null
 },
 "DECK_COUNTS": {
  "DEEDS": 8,
  "FREEDOM-MARKET": 12,
  "COMPETITION": 21
 },
 "OPEN_RULES": [
  {
   "id": "CORE-001",
   "topic": "Factions vs Speculators",
   "question": "Six factions now identified from art (Hartstarr, Stock, Milecastle, Bright, Mina, Nikoyl). Box says 4-6 Speculators. How do they relate? (Each Speculator runs ONE faction, so 4-6 of 6 are in play? Or Speculators are investors who back/trade factions independently?) This mapping drives ownership, alliances, and 'force payment from competitors'.",
   "resolved": null
  },
  {
   "id": "CORE-014",
   "topic": "Faction asymmetry / powers",
   "question": "Do the 6 factions have asymmetric powers, or are they identical engines with different skins? Each FACTIONS entry has mechanical_role=None. (Design read suggests natural leanings — e.g. Bright=supply-flood/price-down, Hartstarr=domestic production, Stock=finance/buyouts, Mina=coercion/chokepoints — but NONE are authored; the designer assigns.)",
   "resolved": null
  },
  {
   "id": "CORE-002",
   "topic": "Three-die system",
   "question": "CORE uses 3 dice; EXPANSION uses 4 dice (designer-confirmed 2026-06-06). Which engine SHAPE: (A) three interchangeable bodies read as one emergent price, or (B) three independent axes each driving a subsystem?",
   "resolved": "Model (A) LOCKED: the 3 core dice are interchangeable bodies read as one emergent market shove (a-2b+c); the player's pip slingshot flips its sign. Supply/Weather/World are the canonical NAMES of the bodies (flavor), NOT separate subsystems (B rejected). Built + validated in oil-engine.js. Open downstream: exact die-face semantics still feed the E.D.D. roll table (CORE-006); B's subsystem flavor returns as card/faction/Green-die hooks, not core."
  },
  {
   "id": "CORE-003",
   "topic": "Drink mechanic",
   "question": "What is the drink mechanic and when does it trigger? No card text references it explicitly; need to know whether any encoded card interacts with it.",
   "resolved": null
  },
  {
   "id": "CORE-004",
   "topic": "E.D.D. price threshold",
   "question": "What is the 'critical threshold' oil price, and on what scale is oil price tracked (range, units, what moves it)? EDD_PROTOCOL.critical_price_threshold is None pending this.",
   "resolved": null
  },
  {
   "id": "CORE-005",
   "topic": "E.D.D. instability condition",
   "question": "What measurable 'global instability condition' must be met alongside the price threshold? Several cards feed 'collapse pressure' / 'hidden collapse pressure' / 'global tension' — is there a single instability meter these all move? EDD_PROTOCOL.instability_condition_value is None pending this.",
   "resolved": null
  },
  {
   "id": "CORE-006",
   "topic": "E.D.D. roll table",
   "question": "What are the relative odds / table layout for EAT vs DIVIDE vs DESTROY? EDD_PROTOCOL.roll_table is None. (Phase 2 will sweep candidate numbers; the designer chooses, the validator reports consequences.)",
   "resolved": null
  },
  {
   "id": "CORE-007",
   "topic": "Pressure/tension meters",
   "question": "Multiple cards move named pressures: 'environmental pressure', 'collapse pressure', 'inflation pressure', 'global tension', 'hidden collapse pressure', 'escalation'. Are these distinct meters or aliases? Phase 2 reachability checks need to know which meter each feeds.",
   "resolved": null
  },
  {
   "id": "CORE-008",
   "topic": "Card type taxonomy",
   "question": "The bible gives parenthetical types unevenly (Legendary Asset, Asset, Market Event, Global Event, Mythic Event) and omits a type on many FREEDOM-MARKET / COMPETITION cards. Is there a fixed type taxonomy every card must carry, or are untyped cards intentionally untyped at concept stage?",
   "resolved": null
  },
  {
   "id": "CORE-009",
   "topic": "Cross-universe: Juice Tanker",
   "question": "'Juice Tanker' exists in ER$N: The Home Game (Core Asset deck) with different mechanics. Do the two stay siblings (shared name, divergent rules) or does one get renamed? Flagged in `scan`. (shared_with_ersn=True)",
   "resolved": null
  },
  {
   "id": "CORE-010",
   "topic": "Candidate-effect selection model",
   "question": "Per card, are the listed candidate effects (a) a menu the player/designer picks ONE from, (b) all-of cumulative, or (c) still being narrowed? All stored verbatim for now; final selection is deferred per the bible.",
   "resolved": "Model (b) ALL-OF, with a COMPETITIVE grammar: each card resolves as ONE bundled effect (no pick-one menu, no choose-UI), and every card must create a SWING — it touches a rival meter (control/barrels/value/exposure/pips) OR moves the shared price level. Pure 'solitaire self-buffs' are banned; self-gain must carry a shared cost or a rival hit. Wired in src/oil-cards.js; proven in src/oil-lab.js analyzeCard/deckIncidence and gated in scripts/oil-lab-check.js (LAB 5: all 41 cards create a swing). Effect NUMBERS stay CONCEPT dials (the designer's to tune/cut); graduating select cards to a real pick-one menu is a later option."
  },
  {
   "id": "CORE-015",
   "topic": "Negotiation / table politics (THE TABLE)",
   "question": "Two cards NAME a diplomacy layer the rules don't describe: 'No Words.' ('negotiations are concluded — they never began') and 'Hobbesian' ('nasty, brutish, and this round'), and CORE-001 names alliances + 'force payment from competitors'. So: how do Speculators deal with each other? Open sub-questions: (a) is a deal binding for a fixed number of turns, or until one side walks? (b) can a deal be made with more than one rival at once (a real cartel), or only pairwise? (c) does the table talk out loud, or is an offer a closed proposal? (d) is the drink mechanic (CORE-003) the seal on a deal — you drink on it? (e) is a broken deal public knowledge, or known only to the two parties?",
   "resolved": null
  },
  {
   "id": "CORE-016",
   "topic": "The board: routes, passages, movement",
   "question": "MAP_OBSERVED describes a Pacific-centered world map whose layers are spatial (LOGISTICS = gold routes/chokepoints), and CORE-001 fixes the 8 HQs as always-present. EDD_PROTOCOL already says 'acquire territory' / 'split region' / 'disable route'. So how do speculators MOVE, and what are the routes? Open sub-questions: (a) THE MOVEMENT READ — model A locked the three bodies as ONE emergent price; is reading them a second time for DISTANCE (the spread, max-min) faithful to 'one roll, read on layers', or should movement be the median die, or not diced at all? (THE LOAD-BEARING ONE.) (b) should the Turkish and Danish Straits be closeable gates — i.e. does the board want interior nodes (Great Lakes, Black Sea littoral) to make them load-bearing? (c) is a faction's own HQ special beyond an incursion bonus — can it be taken? (d) do BARRELS have a location (cargo that must be shipped) or only speculators? (e) what raises a megastructure — control, value, a card, or the Green Anders die? (f) is the Space Elevator's map-bypass the right shape for 'post-oil infrastructure'?",
   "resolved": null
  },
  {
   "id": "CORE-017",
   "topic": "Crisis: flashpoints, blowouts, IWS, annihilation",
   "question": "Designer direction 2026-09-01: lean into the realism of the oil industry (Lessons in Darkness + today's world events) — WAR AND GOVERNMENT DECISIONS driving cleanup and control; IWS/Box & Scooter as the expensive, scarce firefighter service used mostly to clean up AFTER a disaster rather than prevent one; the EXPANSION exacerbating corruption and expense and the effects of both CAPITALISM AND COMMUNISM (the world acting on the companies); MAP-BASED STRESS POINTS AND FLASHPOINTS; and the POTENTIAL FOR ANNIHILATION feeding the collapse meter. Open: (a) what raises heat — cards only, the Green Anders die, faction powers, or a war-and-government deck of its own? (b) is IWS a neutral price everyone pays, or a seat somebody can play (EXPANSION-NOTES calls them a major actor)? (c) is the DRINK (CORE-003) the corruption lever — the thing you do to make a government decision go your way? (d) does annihilation end the game differently (nobody wins) or just sooner? (e) core or expansion — the brief says the EXPANSION exacerbates it, so is there a core-scale crisis the expansion turns up?",
   "resolved": null
  },
  {
   "id": "CORE-011",
   "topic": "Title orthography",
   "question": "Covers render the title as both 'OiL!' and 'OIL!'. TITLE_CANONICAL is set to 'OiL! THE HOME GAME' (lowercase i) as a single source of truth; confirm which is canon so art/docs stop drifting. Flagged in `scan`. (HOUSE RULE 3)",
   "resolved": null
  },
  {
   "id": "CORE-012",
   "topic": "Core vs Expansion split",
   "question": "Box confirms a Core edition (3 dice) and an Expansion (4 dice, requires Core). Beyond the 4th die: which of the encoded cards belong to Core vs Expansion, and what else does the Expansion add (cards? a faction? a meter?)? No card is yet tagged to an edition.",
   "resolved": null
  },
  {
   "id": "CORE-013",
   "topic": "Pump price numbers / oil-price scale",
   "question": "Cover pump faces show prices ($8.18 sale, 1.15 9/10 per gal; grades REG/PLUS/SUPER/PREMIUM/DIESEL). Set-dressing only, or a hint at the oil-price scale E.D.D. reads (CORE-004)? Stored as flavor in ART_OBSERVATIONS until confirmed.",
   "resolved": null
  }
 ]
};
if (typeof window !== 'undefined') window.OIL = OIL;
if (typeof module !== 'undefined' && module.exports) module.exports = OIL;
